server:
  port: 8080

spring:
  application:
    name: identity.service
  config:
    import: "optional:configserver:"
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/parko_db}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update

firebase:
  credentials-path: ${FIREBASE_CREDENTIALS_PATH:F:/Repos/parko-2271f-firebase-adminsdk-fbsvc-95314aaf21.json}
